spring:
  datasource:
    username: admin
    password: admin669 #0开头的数字密码可能会被解析为八进制
    url: jdbc:mysql://localhost:3306/house
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true


mybatis:
  mapper-locations: classpath:mappers/*.xml

qiniu:
  AccessKey: Ksfh7Nh6oJvD9vHDaJWMKu0t06C-FFS2s0x6JTHC
  SecretKey: W36xp8iHEZSbaTEAqvf5MPSBAr5rI6Qxzo24riT8
  Bucket: bianspace
  cdn:
    prefix: http://r17xg53ps.hn-bkt.clouddn.com


#配置分页插件
#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: {count,countSql}

logging:
  levlel:
    com:
      google: debug

